services:

  app:
    image: el-la-la-app
    container_name: el-la-la-telegram-bot
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mariadb:11.5.2
    container_name: el-la-la-db
    volumes:
      - /tmp/el-la-la/var/lib/mysql:/var/lib/mysql
    ports:
      - "3336:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=el-la-la-root-password
      - MYSQL_DATABASE=el-la-la-db
      - MYSQL_USER=el-la-la-user
      - MYSQL_PASSWORD=el-la-la-password
    restart: unless-stopped
